#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Token {
    EndOfInput,
    OpMultiply,
    OpDivide,
    OpMod,
    OpAdd,
    OpSubtract,
    OpNot,
    OpLess,
    OpLessEqual,
    OpGreater,
    OpGreaterEqual,
    OpEqual,
    OpNotEqual,
    OpAssign,
    OpAnd,
    OpOr,
    KeywordIf,
    KeywordElse,
    KeywordWhile,
    KeywordPrint,
    KeywordPutc,
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    Semicolon,
    Comma,
    Indentifier(String),
    Integer(String),
    String (String)
}